### ISSUE TITLE
12 days button state not relayed

### ISSUE THREAD

**Issue by csps-snap** [DIS-SIN/Busrides#106]
##How to reproduce
- use NVDA or another screen reader
- browse through the buttons
- the buttons read "button open 1", "button open 2", etc.

the information about the button's status (locked, unlocked) isn't relayed.

![image](https://user-images.githubusercontent.com/41083520/143489094-6647eaef-73f4-45f9-96ea-81ed5c93da43.png)

**Comment by csps-snap** [comment]
Suggesting the follow:

Remove the SVG from the markup and instead use a <span> with a locked or unlocked tag, same for its content so that the reader will read "button open 12 locked".
use the same SVG but as a background image in the CSS instead. 
(this kind of code can be reused)

**Comment by csps-snap** [comment]
@romy-piche this is solved right ? I thought the PR would close the ticket?

**Comment by romy-piche** [comment]
Yes you are right ! I was just waiting for it to be in production, but now thath it is, I will close the ticket :)
