### ISSUE TITLE
12days - popup feedback

### ISSUE THREAD

**Issue by csps-snap** [DIS-SIN/Busrides#107]
##issue
user is not given any indication that a new window opened

when using NVDA, tabbing through the interface, when hitting "enter", the focus remains on the button, the popup opens, but the focus remains on the button (you can see it more easiliy with NVDA open)

![image](https://user-images.githubusercontent.com/41083520/143489531-368896b1-3f59-40da-a22a-a04aef5bc3e3.png)

**Comment by romy-piche** [comment]
Fixed by: https://github.com/DIS-SIN/Busrides/pull/113
