### ISSUE TITLE
Button appears different in ghost vs prod

### ISSUE THREAD

**Issue by stef-barburou** [DIS-SIN/Busrides#122]
When creating a button element in the Ghost interface, it appears as a button:
![image](https://user-images.githubusercontent.com/41083520/148417400-f5894e8c-b48d-452b-8779-03ecc33be74d.png)

Once published, it appears as a link:

![image](https://user-images.githubusercontent.com/41083520/148417496-4838686a-044a-4202-895e-a771d09bb866.png)

the current example can be found in "The Viability Model Tool – Are you ready for AI?", BUT it currently is **offline**.

**Comment by stef-barburou** [comment]
this is the <a> tag in prod
![image](https://user-images.githubusercontent.com/41083520/148417000-65797856-e039-4750-b3de-dad4ef79097b.png)

**Comment by stef-barburou** [comment]
this is the parent DIV.kg-card.kg-button-card

![image](https://user-images.githubusercontent.com/41083520/148417081-17d48d5f-1596-4c0a-8d2c-028e7ce518b6.png)

**Comment by stef-barburou** [comment]
this is how it looks on prod

![image](https://user-images.githubusercontent.com/41083520/148417232-113db713-ae0c-4081-95b5-1cf99a36d8db.png)

**Comment by stef-barburou** [comment]
it appears that Ghost creates a div with a few classes (kg-card kg-button-card) that aren't styling anything once it reaches prod/react. the div and the <a> tag show absolutely no sign of styling or recognizing those classes.

guessing Ghost has a stylesheet that adds **something** to those classes but it doesn't 'transfer over' ? what do we know about moving ghost's stylesheet over to our project @romy-piche ?

**Comment by romy-piche** [comment]
This is a good question ! 
Do you know if the ghost 'prod' version if affected too ? (can be accessed through https://busrides.ghost.io/, if the episode is published).

**Comment by stef-barburou** [comment]
looks fine and dandy

![image](https://user-images.githubusercontent.com/41083520/148419806-7d8a4090-7ca8-4736-8da3-849d3ce71be1.png)

**Comment by romy-piche** [comment]
Can you see where the css for the kg-button is coming from when using ghost.io ? I don't see it in the source when using the dev tool (app.css)
I think that the styling would need to be added to the react css
