### ISSUE TITLE
meta data coding update 

### ISSUE THREAD

**Issue by stef-barburou** [DIS-SIN/Busrides#139]
. Your meta data coding in your pages does not match with the CSPS site. Please contact Web@ to see what is needed to align these (e.g. you are not using dcterms, which is used by the Canada.ca search).

**Comment by stef-barburou** [comment]
csps website metadata


    <meta content="width=device-width, initial-scale=1" name="viewport">
    <meta name="dcterms.description" lang="en" content="The Canada School of Public Service website provides a broad range of learning opportunities for public servants.">
    <meta name="dcterms.description" lang="fr" content="Le site Web de l'École de la fonction publique du Canada offre un vaste éventail de possibilités d'apprentissage pour les fonctionnaires.">
    <meta name="dcterms.creator" lang="en" content="Canada School of Public Service">
    <meta name="dcterms.creator" lang="fr" content="École de la fonction publique du Canada">
    <meta name="dcterms.title" lang="en" content="Canada School of Public Service">
    <meta name="dcterms.title" lang="fr" content="École de la fonction publique du Canada">
    <meta name="dcterms.issued" title="W3CDTF" content="2020-12-16">
    <meta name="dcterms.modified" title="W3CDTF" content="2020-12-16">
    <meta name="dcterms.subject" lang="en" title="scheme" content="ET Education and Training">
    <meta name="dcterms.subject" lang="fr" title="scheme" content="ET Éducation et formation">
    <meta property="dcterms.language" lang="en" title="ISO639-2/T" content="eng">
    <meta property="dcterms.language" lang="fr" title="ISO639-2" content="fra">
    <meta name="author" lang="en" content="Canada School of Public Service">
    <meta name="author" lang="fr" content="École de la fonction publique du Canada">
    <meta name="robots" content="noindex, follow">

**Comment by stef-barburou** [comment]
busrides meta
<meta name="viewport" content="width=device-width"><meta charset="utf-8">
<meta name="description" content="Busrides is a product of the CSPS Digital Academy, and a destination created to deepen your understanding of everything digital and government.">
<meta property="og:type" content="website">
<meta property="og:url" content="https://busrides-trajetsenbus.csps-efpc.gc.ca/">
<meta property="og:title" content="Busrides">
<meta property="og:description" content="Busrides is a product of the CSPS Digital Academy, and a destination created to deepen your understanding of everything digital and government."><meta property="og:image" content="/thumbnail.jpg">
<meta property="twitter:card" content="summary_large_image"><meta property="twitter:url" content="https://busrides-trajetsenbus.csps-efpc.gc.ca/">
<meta property="twitter:title" content="Busrides">
<meta property="twitter:description" content="Busrides is a product of the CSPS Digital Academy, and a destination created to deepen your understanding of everything digital and government.">
<meta property="twitter:image" content="/thumbnail.jpg"><meta name="next-head-count" content="15">

**Comment by stef-barburou** [comment]
I could see adding these guys, I doubt they'll crete problems but I don't know what's what.
```

<meta name="dcterms.description" lang="en" content="The Canada School of Public Service website provides a broad range of learning opportunities for public servants.">
<meta name="dcterms.description" lang="fr" content="Le site Web de l'École de la fonction publique du Canada offre un vaste éventail de possibilités d'apprentissage pour les fonctionnaires.">
<meta name="dcterms.creator" lang="en" content="Canada School of Public Service">
<meta name="dcterms.creator" lang="fr" content="École de la fonction publique du Canada">
<meta name="dcterms.title" lang="en" content="Canada School of Public Service">
<meta name="dcterms.title" lang="fr" content="École de la fonction publique du Canada">
<meta name="dcterms.issued" title="W3CDTF" content="2020-12-16">
<meta name="dcterms.modified" title="W3CDTF" content="2020-12-16">
<meta name="dcterms.subject" lang="en" title="scheme" content="ET Education and Training">
<meta name="dcterms.subject" lang="fr" title="scheme" content="ET Éducation et formation">
<meta property="dcterms.language" lang="en" title="ISO639-2/T" content="eng">
<meta property="dcterms.language" lang="fr" title="ISO639-2" content="fra">

```

**Comment by stef-barburou** [comment]
I don't know what those guys do, but I get where they'Re going with it
```

<meta name="author" lang="en" content="Canada School of Public Service">
<meta name="author" lang="fr" content="École de la fonction publique du Canada">
<meta name="robots" content="noindex, follow">

```

**Comment by stef-barburou** [comment]
@kroussea @romy-piche 
on rajoute un peu toute pis on espère que ça chie rien ?

**Comment by romy-piche** [comment]
I just don't think it would be possible to have both french and english content in the metadata, since the title/description is straight from a ghost.io post (for an episode at least), and only one language is present. Maybe we could use only one language like www.canada.ca ? 
e.g:

```
<meta name="dcterms.title" content="Home">
<meta name="dcterms.description" content="Get quick, easy access to all Government of Canada services and information.">
<meta name="dcterms.language" title="ISO639-2/T" content="eng">
```

**Comment by romy-piche** [comment]
Do you guys think adding those meta would be alright ?
```
<meta name="author" content={Canada School of Public Service ?}>
<meta name="dcterms.title" content={props.title}>
<meta name="dcterms.description" content={props.description}>
<meta name="dcterms.language" title="ISO639-2/T" content={current language in alpha 3}>
<meta name="dcterms.creator" content={Canada School of Public Service ?}>
<meta name="dcterms.issued" title="W3CDTF" content={updated_at ?}>
<meta name="dcterms.modified" title="W3CDTF" content={updated_at ?}>
<meta name="dcterms.subject" title="scheme" content={ET Education and Training ?}>
```
Might need to confirm the 'author'/'creator', and the 'subject' to use.
For the `robots` meta, i'm not sure what to use as content. I guess omitting it for now would be alright, since the canada.ca site does not use it ?

**Comment by stef-barburou** [comment]
that seems to make sense
