### ISSUE TITLE
GC menu not responding

### ISSUE THREAD

**Issue by stef-barburou** [DIS-SIN/Busrides#165]
the GC menu is not responding 

![image](https://user-images.githubusercontent.com/41083520/152565418-9df0f5fc-cb57-45a6-9e6f-b99a08621801.png)

sitemenu-v5-en file appears missing
![image](https://user-images.githubusercontent.com/41083520/152565476-6421457f-ca61-4c6a-bd52-207403f09edf.png)

in local:

![image](https://user-images.githubusercontent.com/41083520/152565391-03b1fa7e-e09d-43e6-8d80-5becb4dad4cd.png)

**Comment by stef-barburou** [comment]
this is probably WET-update related

**Comment by stef-barburou** [comment]
`                    <ul role="menu" aria-orientation="vertical" data-ajax-replace={`https://wet-boew.github.io/themes-dist/GCWeb/ajax/sitemenu-v5-${props.t.getLocale}.html`}>`

**Comment by romy-piche** [comment]
The link does not work anymore 🤷 
As a hotfix, I will add the menu files directly to the project, using the ones from: https://github.com/wet-boew/GCWeb/releases/tag/v10.4.0

**Comment by romy-piche** [comment]
Ok, better solution. Found the canada cdn for the menu that is working, from the GCWeb doc: https://wet-boew.github.io/GCWeb/docs/
