### ISSUE TITLE
Load more button is unreachable with keyboard

### ISSUE THREAD

**Issue by csps-snap** [DIS-SIN/Busrides#84]
This guy here seems unreachable with a keyboard

![image](https://user-images.githubusercontent.com/41083520/138284053-91357eec-7e89-446f-98fe-049c5fc14aa5.png)

**Comment by csps-snap** [comment]
perfect, next step would be to provide feedback after the button is pressed. this can be tricky.

**Comment by romy-piche** [comment]
I added the **aria-live="polite"** property for the episode list region, but i'm not sure if this is enough!
