### ISSUE TITLE
Accessible options : labels are unclear

### ISSUE THREAD

**Issue by csps-snap** [DIS-SIN/Busrides#87]
In the top Accessible options, the buttons need better labels, otherwise they're confusing

Here we have  "clickable button" and "plus button" which would probably leave some blind users clueless

for example, you could use "greyscale" as a label instead of a P tag so that when you reach the checkbox it reads the label. maybe even add an invisible (span.wb-inv) "toggle" for clarity

![image](https://user-images.githubusercontent.com/41083520/138285964-0aec481b-5dec-4303-96d5-3623bc70a2c8.png)

**Comment by romy-piche** [comment]
Labels for the accessible button has been added !
