### ISSUE TITLE
Language synthetizer not switching to french in label

### ISSUE THREAD

**Issue by csps-snap** [DIS-SIN/Busrides#88]
this may require more work than worth it, but the label only reads in the current language.
to fix this, you'd probably need to use an entire element and have a span inside it withe the lang tag... and then maybe use aria-labelledby to point to it with an ID
![image](https://user-images.githubusercontent.com/41083520/138287515-8ccced3d-5fa0-497f-83a9-cb1fdc101cf9.png)

**Comment by csps-snap** [comment]
spent 1h on this issue
found out the french is loaded from ghost, and it seems to be some sort of account name, so we won't be able to modify it to incorporate span tags to mark the language switch.

is this correct @romy-piche  ? 

if so, nothing much can be done, we can close the ticket

**Comment by romy-piche** [comment]
Oh yeah ! You are right, the author name comes from ghost directly and it's the account Full Name: https://busrides.ghost.io/ghost/#/settings/staff/da

As you said, I don't think much can be done for this case.

**Comment by csps-snap** [comment]
closing.
