### ISSUE TITLE
gif animation requires long description

### ISSUE THREAD

**Issue by csps-snap** [DIS-SIN/Busrides#90]
gif animation requires long description

example: 
https://busrides-trajetsenbus.csps-efpc.gc.ca/en/ep-50-en

not going to go through the entire site for these, but graphs need descriptions.
suggesting an alt that says "see long description below" and add a details box named "long description"

![image](https://user-images.githubusercontent.com/41083520/138297511-6b2c1e0c-ab9e-4322-8279-2ebefc7b011b.png)

**Comment by veeDA21** [comment]
completed!

**Comment by csps-snap** [comment]
suggesting adding contenxt
![image](https://user-images.githubusercontent.com/41083520/140059503-8b90d3d3-64ae-4dbc-be74-a8f7e67cb133.png)

also "data as of january every year, lower and upper houses combined, source : inter-parliamentary union)
